
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DeployId:
    Type: String
    Default: afsf34sfdg
  SourceCodeBucket:
    Type: String
    Default: afsf34sfdg
Resources:
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        openapi: "3.0.1"
        info:
          title: "EducativeRestAPI"
          description: "Rest API for Educative API Gateway Course"
          version: "2022-06-06T10:08:49Z"
        paths:
          /whereami:
            post:
              responses:
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-integration:
                httpMethod: "POST"
                uri: "https://public.krazyminds.com/ipinfo"
                responses:
                  default:
                    statusCode: "200"
                requestTemplates:
                  application/json: "{\n  \"ip\": \"$context.identity.sourceIp\"\n}"
                passthroughBehavior: "when_no_templates"
                type: "http"
        components:
          schemas:
            Empty:
              title: "Empty Schema"
              type: "object"
      Name: EducativeRestAPI
      Description: "Rest API for Educative API Gateway Course"
      Mode: overwrite
